all:
  children:
    webservers:
      hosts:
        vm1:
          ansible_host: 158.160.50.115
        vm2:
          ansible_host: 158.160.61.55
        vm3:
          ansible_host: 89.169.149.163
      vars:
        ansible_user: ubuntu 